#You have to configure here your environment var

I_WAS_HERE_BADGE: "i-was-here"
WELCOME_BACK_BADGE: "welcome-back"
#SECRET_KEY_BASE: key0f3x4mpl3f82c91101361593c8a15847d4bb64d2624598b25f3e8a7ec4c08f25dd08ffd5a3ee
#DATABASE_NAME: "databasename"
#DATABASE_USERNAME: "databaseusername"
#DATABASE_PASSWORD: "databasepass"

